CREATE TABLE IF NOT EXISTS `agents` (
		`idx` int(11) NOT NULL AUTO_INCREMENT,
		`newConfig` tinyint(1) NOT NULL DEFAULT '0',
		`agent_id` char(20),
		`time` int(11),
		`status` varchar(15),
		`agent_ip` char(15),
		`FilterExpression` varchar(1024),
		`agent_alias` char(128),
		`agent_type` char(128),
		`pipe_file` varchar(100),
		`ATMSPort` varchar(5),
		`MaxHeadersLength` varchar(10),
		`MaxGetParamsLength` varchar(10),
		`MaxPostLength` varchar(10),
		`StatusInterval` int(11),
		`CookieExpireTime` int(11),
		`ConcurrentSessions` varchar(10),
		`MessagesQueueSize` varchar(10),
		`owner_user` char(20),
		`owner_group` char(20),
		`msg_id` bigint(20) unsigned,
		`NetworkInterface` char(64),
		`fingerprint_headers` varchar(4096),
		PRIMARY KEY (`idx`),
		UNIQUE KEY `agent_id` (`agent_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;