CREATE TABLE IF NOT EXISTS `request_scores_user` (
		`production` tinyint(1) NOT NULL,
		`RID` bigint(20) NOT NULL,
		`SID` varchar(100) NOT NULL,
		`seq_index` int(5) unsigned zerofill NOT NULL,
		`SID_status` enum('valid','invalid','unknown') NOT NULL DEFAULT 'unknown',
		`hostname` int(10) unsigned NOT NULL,
		`page_id` int(11) NOT NULL,
		`status_code` int(3) unsigned NOT NULL,
		`protocol` enum('HTTP','HTTPS') CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT 'HTTP',
		`method` enum('GET','POST','HEAD','OPTIONS','PUT','DELETE','TRACE','CONNECT','PROPFIND','PROPPATCH','MKCOL','COPY','MOVE','LOCK','UNLOCK','POLL','REPORT','SUBSCRIBE','BMOVE','SEARCH') NOT NULL DEFAULT 'GET',
		`AgentID` char(25) CHARACTER SET utf8 NOT NULL,
		`user_id` int(10) unsigned NOT NULL,
		`user_ip` char(18) CHARACTER SET utf8 NOT NULL,
		`country` char(2) NOT NULL DEFAULT '00',
		`city` char(40) CHARACTER SET utf8 NOT NULL,
		`latitude` double NOT NULL,
		`longitude` double NOT NULL,
		`query_score` double NOT NULL,
		`flow_score` double NOT NULL,
		`landing_normal` double NOT NULL,
		`geo_normal` double NOT NULL,
		`avg_score` double NOT NULL,
		`date` bigint(20) unsigned NOT NULL,
		PRIMARY KEY (`RID`),
		KEY `rs_page_id` (`page_id`),
		KEY `SID` (`SID`),
		KEY `avg_score` (`avg_score`),
		KEY `date_index` (`date`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
