/*
 * File: app/view/changesSavedError.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.changesSavedError', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Label',
        'Ext.Img'
    ],

    draggable: false,
    height: 110,
    id: 'changesSavedError',
    width: 280,
    resizable: false,
    layout: 'absolute',
    closable: false,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    x: 90,
                    y: 40,
                    style: 'font-weight:bold',
                    text: 'An Error Has Occurred'
                },
                {
                    xtype: 'image',
                    x: 20,
                    y: 20,
                    height: 50,
                    width: 50,
                    src: 'Htmls/images/error.gif'
                }
            ],
            listeners: {
                hide: {
                    fn: me.onChangesSavedErrorHide,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onChangesSavedErrorHide: function(component, eOpts) {
        component.destroy();
    }

});