/*
 * File: app/view/d_mapLarge.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.d_mapLarge', {
    extend: 'Ext.window.Window',

    height: 480,
    id: 'd_mapLarge',
    minHeight: 480,
    minWidth: 640,
    width: 640,
    resizable: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                show: {
                    fn: me.onD_mapLargeShow,
                    scope: me
                },
                destroy: {
                    fn: me.onD_mapLargeDestroy,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onD_mapLargeShow: function(component, eOpts) {
        Ext.getCmp('main_panel').disable();
        var win = Ext.WindowManager.get('d_mapLarge');
        var width = $(document).width();
        var height = $(document).height();
        win.setPosition(width*0.16,40);
        win.setHeight(height*0.66);
        win.setWidth(width*0.66);
        setTimeout(function(){
            setMapData();
        },3000);
    },

    onD_mapLargeDestroy: function(component, eOpts) {
        Ext.getCmp('main_panel').enable();
    }

});