/*
 * File: app/view/DeleteRule.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DeleteRule', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.Img'
    ],

    draggable: false,
    height: 137,
    id: 'DeleteRule',
    width: 389,
    resizable: false,
    layout: 'absolute',
    closable: false,
    title: 'Delete Group',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    x: 120,
                    y: 60,
                    icon: 'Htmls/images/check.png',
                    text: 'Yes',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 190,
                    y: 60,
                    icon: 'Htmls/images/x.gif',
                    text: 'No',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 20,
                    id: 'b_delete_text',
                    text: 'Are you sure you want to delete this rule?'
                },
                {
                    xtype: 'image',
                    x: 20,
                    y: 10,
                    height: 30,
                    width: 30,
                    src: 'Htmls/images/delete.gif'
                }
            ],
            listeners: {
                show: {
                    fn: me.onDeleteRuleShow,
                    scope: me
                },
                destroy: {
                    fn: me.onDeleteRuleDestroy,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        delete_rule_or_group();
    },

    onButtonClick1: function(button, e, eOpts) {
        Ext.WindowManager.get("DeleteRule").destroy()
    },

    onDeleteRuleShow: function(component, eOpts) {
        Ext.getCmp("main_panel").disable();
        var node = Ext.getCmp('b_ruleGroups').getSelectionModel().getSelection()[0];
        if (node.data.type=='rule'){
            Ext.getCmp('DeleteRule').header.setTitle('Delete criterion');
            Ext.getCmp('b_delete_text').setText('Are you sure you want to delete this criterion?');
        }
        else if(node.data.type=='group'){
            Ext.getCmp('DeleteRule').header.setTitle('Delete rule');
            Ext.getCmp('b_delete_text').setText('Are you sure you want to delete this rule?');
        }
        else if(node.data.type=='category'){
            Ext.getCmp('DeleteRule').header.setTitle('Delete category');
            Ext.getCmp('b_delete_text').setText('Are you sure you want to delete this category?');
        }

    },

    onDeleteRuleDestroy: function(component, eOpts) {
        Ext.getCmp("main_panel").enable();
    }

});