CREATE TABLE IF NOT EXISTS `applications` (
		`ldap_conn` varchar(1024),
		`app_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
		`app_domain` varchar(1024),
		`app_type` varchar(100),
		`display_name` varchar(1024) NOT NULL DEFAULT '',
		`login_att_id` varchar(20),
		`ntlm` tinyint(1) unsigned zerofill,
		`logged_condition` varchar(1024),
		`condition_value` char(1),
		`logout_page_id` varchar(200),
		`logout_att_id` varchar(200),
		`logout_att_value` varchar(200),
		`AppCookieName` char(255),
	        `cookie_suggestion` char(255),
		`cpt_name` varchar(250),
		`cpt_val` varchar(250),
		`global_per_app` int(1),
		`exclude_group_headers` varchar(4096),
		`global_pages` varchar(4096),
		`dirty` tinyint(1),
		`certificate` mediumtext,
		`private_key` mediumtext,
		`ssl_flag` tinyint(1),
		`ssl_server_port` varchar(10),
		`app_ips` longtext,
		`ssl_certificate_password` varchar(100),
		`certificate_flag` tinyint(4) NOT NULL DEFAULT 0,
		`private_key_flag` tinyint(4) NOT NULL DEFAULT 0,
		`certificate_path` varchar(100),
		`private_key_path` varchar(100),
		`cpt_injected_header_name` varchar(100),
		`basic_flag` tinyint(4) NOT NULL DEFAULT 0,
		`digest_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_param_id` int(11),
		`form_param_name` varchar(100),
		`form_authentication_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_authentication_cookie_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_authentication_redirect_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_authentication_redirect_page_id` int(11),
		`form_authentication_redirect_page_name` varchar(100),
		`form_authentication_redirect_response_range` varchar(100),
		`form_authentication_body_flag` tinyint(4),
		`form_authentication_body_value` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '',
		`form_authentication_cookie_name` varchar(100),
		`form_authentication_cookie_value` varchar(100),
		`form_logout_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_logout_cookie_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_logout_redirect_flag` tinyint(4) NOT NULL DEFAULT 0,
		`form_logout_redirect_page_id` int(11),
		`form_logout_redirect_page_name` varchar(100),
		`form_logout_redirect_response_range` varchar(100),
		`form_logout_body_flag` tinyint(4),
		`form_logout_body_value` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
		`form_logout_cookie_name` varchar(100),
		`form_logout_cookie_value` varchar(100),
		PRIMARY KEY (`app_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
