CREATE TABLE IF NOT EXISTS `rules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(256) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '-',
  `aspect` varchar(128) DEFAULT '',
  `description` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '-',
  `appearance` int(11) DEFAULT '1',
  `anchor_type` varchar(10) DEFAULT '',
  `anchor` varchar(128) DEFAULT '',
  `dynamic_type` varchar(10) DEFAULT '',
  `att_id` varchar(128) DEFAULT '',
  `att_name` varchar(128) DEFAULT '',
  `pr_attrType` varchar(25) DEFAULT '',
  `str_match` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '',
  `not_signal` tinyint(1) DEFAULT '0',
  `str_length` varchar(15) DEFAULT '',
  `str_similarity` int(11) DEFAULT '0',
  `page_id` bigint(20) unsigned DEFAULT '0',
  `business_id` int(11) DEFAULT '0',
  `numeric_score` varchar(10) DEFAULT '',
  `literal_score` varchar(128) DEFAULT '',
  `count` varchar(32) DEFAULT '',
  `seq_index` varchar(10) DEFAULT '',
  `time` varchar(10) DEFAULT '',
  `radius` double DEFAULT '0',
  `user` varchar(256) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '',
  `user_ip` varchar(1000) DEFAULT '',
  `ip_neg` tinyint(1) DEFAULT '0',
  `app_id` varchar(50) DEFAULT '',
  `rule_group` int(10) unsigned DEFAULT '0',
  `occurence` varchar(15) DEFAULT '',
  `owner` varchar(256) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT '',
  `rule_type` varchar(20) DEFAULT '',
  `timetype` varchar(5) DEFAULT '',
  `personal` tinyint(1) DEFAULT '0',
  `enable_rule` tinyint(1) DEFAULT '1',
  `buildup` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=712 ;
