/*
 * File: app/view/permissionWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.permissionWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.TextArea'
    ],

    height: 329,
    id: 'permissionWindow',
    width: 512,
    layout: 'absolute',
    title: 'Permission Editor',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save Permission',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'perm_delete',
                            text: 'Delete Permission',
                            listeners: {
                                click: {
                                    fn: me.onPermission_deleteClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'perm_activity',
                            text: 'View Activity'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 10,
                    id: 'perm_class',
                    width: 240,
                    fieldLabel: 'Class'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 40,
                    id: 'perm_function',
                    width: 240,
                    fieldLabel: 'Function'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 70,
                    id: 'perm_alias',
                    width: 240,
                    fieldLabel: 'Alias'
                },
                {
                    xtype: 'gridpanel',
                    x: 260,
                    y: 10,
                    height: 220,
                    id: 'perm_applications',
                    width: 230,
                    title: 'Application Selection',
                    store: 'applicationsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'domain',
                            text: 'Application',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        checkOnly: true
                    })
                },
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 100,
                    height: 126,
                    id: 'perm_description',
                    width: 240,
                    fieldLabel: 'Description',
                    labelAlign: 'top'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 240,
                    id: 'perm_params',
                    width: 480,
                    fieldLabel: 'Additional Parameters',
                    labelWidth: 150
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        telepath.permissions.save();
    },

    onPermission_deleteClick: function(button, e, eOpts) {
        telepath.permissions.deleteClick();
    }

});