/*
 * File: app/view/systemViewPort.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.systemViewPort', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    height: 250,
                    id: 'systemPanel',
                    width: 400,
                    layout: 'fit',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            height: 30,
                            id: 'systemToolbar'
                        }
                    ]
                }
            ],
            listeners: {
                render: {
                    fn: me.onViewportRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onViewportRender: function(component, eOpts) {
        telepath.system.render(component);
    }

});