/*
 * File: app/view/trial_ended.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.trial_ended', {
    extend: 'Ext.window.Window',

    height: 293,
    id: 'trial_ended',
    width: 442,
    layout: {
        type: 'absolute'
    },
    closable: false,
    titleCollapse: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    x: 80,
                    y: 20,
                    height: 90,
                    width: 260,
                    src: 'images/logo.png'
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 140,
                    width: 250,
                    text: 'Dear customer,'
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 160,
                    text: 'Thank you for trying Hybrid Telepath.'
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 180,
                    text: 'The trial period has ended. If you\'re interested in purchasing'
                },
                {
                    xtype: 'label',
                    x: 60,
                    y: 200,
                    text: 'Hybrid Telepath, please leave contact details  '
                },
                {
                    xtype: 'displayfield',
                    x: 310,
                    y: 196,
                    fieldLabel: '',
                    value: '<a href="http://hybridsec.com/contact.php" target=\'_blank\'>on our website</a>'
                }
            ]
        });

        me.callParent(arguments);
    }

});