/*
 * File: app/view/appEdit_Error.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.appEdit_Error', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Label',
        'Ext.Img'
    ],

    draggable: false,
    height: 125,
    id: 'appEdit_Error',
    width: 336,
    resizable: false,
    layout: 'absolute',
    closable: false,
    title: 'Error',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    x: 100,
                    y: 35,
                    text: 'Please Select One Application to Edit'
                },
                {
                    xtype: 'image',
                    x: 30,
                    y: 20,
                    height: 50,
                    width: 50,
                    src: 'Htmls/images/error.gif'
                }
            ]
        });

        me.callParent(arguments);
    }

});