/*
 * File: app/view/ipConfig.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ipConfig', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.container.Container'
    ],

    height: 212,
    id: 'ipConfig',
    width: 182,
    layout: 'absolute',
    title: 'IP Configuration',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 80,
                    y: 10,
                    id: 'ipConfig_mode_switch',
                    width: 80,
                    value: 'Single IP',
                    store: [
                        'Single IP',
                        'IP Range'
                    ],
                    listeners: {
                        change: {
                            fn: me.onIpConfig_mode_switchChange,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 110,
                    y: 150,
                    width: 50,
                    text: 'Apply',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 50,
                    y: 150,
                    width: 50,
                    text: 'Cancel',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 40,
                    height: 20,
                    id: 'ipConfig_label_1',
                    width: 150,
                    text: 'Range From:'
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 90,
                    disabled: true,
                    height: 20,
                    id: 'ipConfig_label_2',
                    width: 150,
                    text: 'Range End:'
                },
                {
                    xtype: 'container',
                    x: 10,
                    y: 60,
                    height: 30,
                    id: 'ipConfig_range_start',
                    width: 150,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 0,
                            id: 'ipConfig_segment_0_0',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 1,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 0,
                            id: 'ipConfig_segment_0_1',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 2,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 80,
                            y: 0,
                            id: 'ipConfig_segment_0_2',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 3,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 120,
                            y: 0,
                            id: 'ipConfig_segment_0_3',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 4,
                            allowBlank: false
                        },
                        {
                            xtype: 'label',
                            x: 32,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        },
                        {
                            xtype: 'label',
                            x: 112,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        },
                        {
                            xtype: 'label',
                            x: 72,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    x: 10,
                    y: 110,
                    height: 30,
                    id: 'ipConfig_range_end',
                    width: 150,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 0,
                            id: 'ipConfig_segment_1_0',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 5,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 0,
                            id: 'ipConfig_segment_1_1',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 6,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 80,
                            y: 0,
                            id: 'ipConfig_segment_1_2',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 7,
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            x: 120,
                            y: 0,
                            id: 'ipConfig_segment_1_3',
                            width: 30,
                            fieldLabel: '',
                            tabIndex: 8,
                            allowBlank: false
                        },
                        {
                            xtype: 'label',
                            x: 32,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        },
                        {
                            xtype: 'label',
                            x: 72,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        },
                        {
                            xtype: 'label',
                            x: 112,
                            y: 0,
                            height: 20,
                            style: 'font-size: 18px;',
                            width: 10,
                            text: '.'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onIpConfig_mode_switchChange: function(field, newValue, oldValue, eOpts) {
        telepath.ipconfig.modeSwitch(newValue);
    },

    onButtonClick1: function(button, e, eOpts) {
        telepath.ipconfig.applyClick();
    },

    onButtonClick: function(button, e, eOpts) {
        telepath.ipconfig.cancelClick();
    }

});