/*
 * File: app/view/ruleEdited_failure.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ruleEdited_failure', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.Img',
        'Ext.form.Label'
    ],

    height: 156,
    id: 'ruleEdited_failure',
    width: 320,
    layout: 'absolute',
    title: 'Info',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    x: 40,
                    y: 20,
                    height: 60,
                    width: 60,
                    src: 'Htmls/images/error.gif'
                },
                {
                    xtype: 'label',
                    x: 130,
                    y: 40,
                    style: 'font-weight:bold;',
                    text: 'An Error Has Occured'
                }
            ],
            listeners: {
                hide: {
                    fn: me.onRuleEdited_failureHide,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onRuleEdited_failureHide: function(component, eOpts) {
        component.destroy();
    }

});