/*
 * File: app/view/AppTreeWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AppTreeWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.AppTreePanel'
    ],

    height: 562,
    width: 923,
    constrain: true,
    layout: {
        type: 'fit'
    },
    title: 'Applications',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'apptreepanel',
                    height: 456,
                    width: 805,
                    forceFit: false
                }
            ]
        });

        me.callParent(arguments);
    }

});