/*
 * File: app/view/AppTreePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AppTreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.apptreepanel',

    id: '',
    width: 600,
    header: false,
    title: 'Telepath',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'text',
                    text: 'Nodes',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'value',
                    text: 'Value'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    hidden: true,
                    itemId: 'AppTreeTopBar',
                    width: 400
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoRender: true,
                    itemId: 'AppTreeSearch',
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'AppTreeSearchInput',
                            padding: '0px 0px 0px 10px',
                            width: 169,
                            fieldLabel: 'Search',
                            labelWidth: 60
                        },
                        {
                            xtype: 'radiofield',
                            cls: 'app-tree-search-type',
                            itemId: 'AppTreeSearchPages',
                            padding: '0px 0px 0px 10px',
                            fieldLabel: '',
                            hideLabel: true,
                            name: 'AppTreeSearchType',
                            submitValue: false,
                            value: 0,
                            boxLabel: 'Page',
                            inputValue: ''
                        },
                        {
                            xtype: 'radiofield',
                            cls: 'app-tree-search-type',
                            itemId: 'AppTreeSearchParams',
                            padding: '0px 0px 0px 10px',
                            fieldLabel: '',
                            hideLabel: true,
                            name: 'AppTreeSearchType',
                            submitValue: false,
                            value: 1,
                            boxLabel: 'Param',
                            inputValue: ''
                        },
                        {
                            xtype: 'radiofield',
                            cls: 'app-tree-search-type',
                            itemId: 'AppTreeSearchApps',
                            padding: '0px 0px 0px 10px',
                            fieldLabel: '',
                            hideLabel: true,
                            name: 'AppTreeSearchType',
                            submitValue: false,
                            value: 1,
                            boxLabel: 'App',
							checked: true,
                            inputValue: ''
                        },
                        {
                            xtype: 'button',
                            itemId: 'AppTreeSearchButton',
                            margin: '0px 0px 0px 10px',
                            iconCls: 'icon-search',
                            text: 'Search'
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    autoRender: true,
                    itemId: 'AppTreeToolbar'
                }
            ]
        });

        me.callParent(arguments);
    }

});