var aliasToName = {
"AP":"Asia/Pacific Region",
"AF":"Afghanistan",
"AX":"Aland Islands",
"AL":"Albania",
"DZ":"Algeria",
"AS":"American Samoa",
"AD":"Andorra",
"AO":"Angola",
"AI":"Anguilla",
"A1":"Anonymous Proxy",
"AQ":"Antarctica",
"AG":"Antigua and Barbuda",
"AR":"Argentina",
"AM":"Armenia",
"AW":"Aruba",
"AU":"Australia",
"AT":"Austria",
"AZ":"Azerbaijan",
"BS":"Bahamas",
"BH":"Bahrain",
"BD":"Bangladesh",
"BB":"Barbados",
"BY":"Belarus",
"BE":"Belgium",
"BZ":"Belize",
"BJ":"Benin",
"BM":"Bermuda",
"BT":"Bhutan",
"BO":"Bolivia",
"BQ":"Bonaire, Saint Eustatius and Saba",
"BA":"Bosnia and Herzegovina",
"BW":"Botswana",
"BV":"Bouvet Island",
"BR":"Brazil",
"IO":"British Indian Ocean Territory",
"BN":"Brunei Darussalam",
"BG":"Bulgaria",
"BF":"Burkina Faso",
"BI":"Burundi",
"KH":"Cambodia",
"CM":"Cameroon",
"CA":"Canada",
"CV":"Cape Verde",
"KY":"Cayman Islands",
"CF":"Central African Republic",
"TD":"Chad",
"CL":"Chile",
"CN":"China",
"CX":"Christmas Island",
"CC":"Cocos (Keeling) Islands",
"CO":"Colombia",
"KM":"Comoros",
"CD":"Congo, The Democratic Republic of the",
"CG":"Congo",
"CK":"Cook Islands",
"CR":"Costa Rica",
"CI":"Cote D'Ivoire",
"HR":"Croatia",
"CU":"Cuba",
"CW":"Curacao",
"CY":"Cyprus",
"CZ":"Czech Republic",
"DK":"Denmark",
"DJ":"Djibouti",
"DM":"Dominica",
"DO":"Dominican Republic",
"EC":"Ecuador",
"EG":"Egypt",
"SV":"El Salvador",
"GQ":"Equatorial Guinea",
"ER":"Eritrea",
"EE":"Estonia",
"ET":"Ethiopia",
"EU":"Europe",
"FK":"Falkland Islands (Malvinas)",
"FO":"Faroe Islands",
"FJ":"Fiji",
"FI":"Finland",
"FR":"France",
"GF":"French Guiana",
"PF":"French Polynesia",
"TF":"French Southern Territories",
"GA":"Gabon",
"GM":"Gambia",
"GE":"Georgia",
"DE":"Germany",
"GH":"Ghana",
"GI":"Gibraltar",
"GR":"Greece",
"GL":"Greenland",
"GD":"Grenada",
"GP":"Guadeloupe",
"GU":"Guam",
"GT":"Guatemala",
"GG":"Guernsey",
"GW":"Guinea-Bissau",
"GN":"Guinea",
"GY":"Guyana",
"HT":"Haiti",
"HM":"Heard Island and McDonald Islands",
"VA":"Holy See (Vatican City State)",
"HN":"Honduras",
"HK":"Hong Kong",
"HU":"Hungary",
"IS":"Iceland",
"IN":"India",
"ID":"Indonesia",
"IR":"Iran, Islamic Republic of",
"IQ":"Iraq",
"IE":"Ireland",
"IM":"Isle of Man",
"IL":"Israel",
"IT":"Italy",
"JM":"Jamaica",
"JP":"Japan",
"JE":"Jersey",
"JO":"Jordan",
"KZ":"Kazakhstan",
"KE":"Kenya",
"KI":"Kiribati",
"KP":"Korea, Democratic People's Republic of",
"KR":"Korea, Republic of",
"KW":"Kuwait",
"KG":"Kyrgyzstan",
"LA":"Lao People's Democratic Republic",
"LV":"Latvia",
"LB":"Lebanon",
"LS":"Lesotho",
"LR":"Liberia",
"LY":"Libya",
"LI":"Liechtenstein",
"LT":"Lithuania",
"LU":"Luxembourg",
"MO":"Macau",
"MK":"Macedonia",
"MG":"Madagascar",
"MW":"Malawi",
"MY":"Malaysia",
"MV":"Maldives",
"ML":"Mali",
"MT":"Malta",
"MH":"Marshall Islands",
"MQ":"Martinique",
"MR":"Mauritania",
"MU":"Mauritius",
"YT":"Mayotte",
"MX":"Mexico",
"FM":"Micronesia, Federated States of",
"MD":"Moldova, Republic of",
"MC":"Monaco",
"MN":"Mongolia",
"ME":"Montenegro",
"MS":"Montserrat",
"MA":"Morocco",
"MZ":"Mozambique",
"MM":"Myanmar",
"NA":"Namibia",
"NR":"Nauru",
"NP":"Nepal",
"NL":"Netherlands",
"NC":"New Caledonia",
"NZ":"New Zealand",
"NI":"Nicaragua",
"NE":"Niger",
"NG":"Nigeria",
"NU":"Niue",
"NF":"Norfolk Island",
"MP":"Northern Mariana Islands",
"NO":"Norway",
"OM":"Oman",
"O1":"Other",
"PK":"Pakistan",
"PW":"Palau",
"PS":"Palestinian Territory",
"PA":"Panama",
"PG":"Papua New Guinea",
"PY":"Paraguay",
"PE":"Peru",
"PH":"Philippines",
"PN":"Pitcairn Islands",
"PL":"Poland",
"PT":"Portugal",
"PR":"Puerto Rico",
"QA":"Qatar",
"RE":"Reunion",
"RO":"Romania",
"RU":"Russian Federation",
"RW":"Rwanda",
"BL":"Saint Barthelemy",
"SH":"Saint Helena",
"KN":"Saint Kitts and Nevis",
"LC":"Saint Lucia",
"MF":"Saint Martin",
"PM":"Saint Pierre and Miquelon",
"VC":"Saint Vincent and the Grenadines",
"WS":"Samoa",
"SM":"San Marino",
"ST":"Sao Tome and Principe",
"A2":"Satellite Provider",
"SA":"Saudi Arabia",
"SN":"Senegal",
"RS":"Serbia",
"SC":"Seychelles",
"SL":"Sierra Leone",
"SG":"Singapore",
"SX":"Sint Maarten (Dutch part)",
"SK":"Slovakia",
"SI":"Slovenia",
"SB":"Solomon Islands",
"SO":"Somalia",
"ZA":"South Africa",
"GS":"South Georgia and the South Sandwich Islands",
"ES":"Spain",
"LK":"Sri Lanka",
"SD":"Sudan",
"SR":"Suriname",
"SJ":"Svalbard and Jan Mayen",
"SZ":"Swaziland",
"SE":"Sweden",
"CH":"Switzerland",
"SY":"Syrian Arab Republic",
"TW":"Taiwan",
"TJ":"Tajikistan",
"TZ":"Tanzania, United Republic of",
"TH":"Thailand",
"TL":"Timor-Leste",
"TG":"Togo",
"TK":"Tokelau",
"TO":"Tonga",
"TT":"Trinidad and Tobago",
"TN":"Tunisia",
"TR":"Turkey",
"TM":"Turkmenistan",
"TC":"Turks and Caicos Islands",
"TV":"Tuvalu",
"UG":"Uganda",
"UA":"Ukraine",
"AE":"United Arab Emirates",
"GB":"United Kingdom",
"UM":"United States Minor Outlying Islands",
"US":"United States",
"UY":"Uruguay",
"UZ":"Uzbekistan",
"VU":"Vanuatu",
"VE":"Venezuela",
"VN":"Vietnam",
"VG":"Virgin Islands, British",
"VI":"Virgin Islands, U.S.",
"WF":"Wallis and Futuna",
"EH":"Western Sahara",
"YE":"Yemen",
"ZM":"Zambia",
"ZW":"Zimbabwe",
"00":"Unknown"
}

var nameToAlias = {
	'Unknown' : '00',
	'Asia/Pacific Region':'AP',
	'Europe':'EU',
	'Andorra':'AD',
	'United Arab Emirates':'AE',
	'Afghanistan':'AF',
	'Antigua and Barbuda':'AG',
	'Anguilla':'AI',
	'Albania':'AL',
	'Armenia':'AM',
	'Curacao':'CW',
	'Angola':'AO',
	'Antarctica':'AQ',
	'Argentina':'AR',
	'American Samoa':'AS',
	'Austria':'AT',
	'Australia':'AU',
	'Aruba':'AW',
	'Azerbaijan':'AZ',
	'Bosnia and Herzegovina':'BA',
	'Barbados':'BB',
	'Bangladesh':'BD',
	'Belgium':'BE',
	'Burkina Faso':'BF',
	'Bulgaria':'BG',
	'Bahrain':'BH',
	'Burundi':'BI',
	'Benin':'BJ',
	'Bermuda':'BM',
	'Brunei Darussalam':'BN',
	'Bolivia':'BO',
	'Brazil':'BR',
	'Bahamas':'BS',
	'Bhutan':'BT',
	'Bouvet Island':'BV',
	'Botswana':'BW',
	'Belarus':'BY',
	'Belize':'BZ',
	'Canada':'CA',
	'Cocos (Keeling) Islands':'CC',
	'Congo, The Democratic Republic of the':'CD',
	'Central African Republic':'CF',
	'Congo':'CG',
	'Switzerland':'CH',
	'Cote D\'Ivoire':'CI',
	'Cook Islands':'CK',
	'Chile':'CL',
	'Cameroon':'CM',
	'China':'CN',
	'Colombia':'CO',
	'Costa Rica':'CR',
	'Cuba':'CU',
	'Cape Verde':'CV',
	'Christmas Island':'CX',
	'Cyprus':'CY',
	'Czech Republic':'CZ',
	'Germany':'DE',
	'Djibouti':'DJ',
	'Denmark':'DK',
	'Dominica':'DM',
	'Dominican Republic':'DO',
	'Algeria':'DZ',
	'Ecuador':'EC',
	'Estonia':'EE',
	'Egypt':'EG',
	'Western Sahara':'EH',
	'Eritrea':'ER',
	'Spain':'ES',
	'Ethiopia':'ET',
	'Finland':'FI',
	'Fiji':'FJ',
	'Falkland Islands (Malvinas)':'FK',
	'Micronesia, Federated States of':'FM',
	'Faroe Islands':'FO',
	'France':'FR',
	//'Sint Maarten (Dutch part)':'SX',
	'Gabon':'GA',
	'United Kingdom':'GB',
	'Grenada':'GD',
	'Georgia':'GE',
	'French Guiana':'GF',
	'Ghana':'GH',
	'Gibraltar':'GI',
	'Greenland':'GL',
	'Gambia':'GM',
	'Guinea':'GN',
	'Guadeloupe':'GP',
	'Equatorial Guinea':'GQ',
	'Greece':'GR',
	'South Georgia and the South Sandwich Islands':'GS',
	'Guatemala':'GT',
	'Guam':'GU',
	'Guinea-Bissau':'GW',
	'Guyana':'GY',
	'Hong Kong':'HK',
	'Heard Island and McDonald Islands':'HM',
	'Honduras':'HN',
	'Croatia':'HR',
	'Haiti':'HT',
	'Hungary':'HU',
	'Indonesia':'ID',
	'Ireland':'IE',
	'Israel':'IL',
	'India':'IN',
	'British Indian Ocean Territory':'IO',
	'Iraq':'IQ',
	'Iran, Islamic Republic of':'IR',
	'Iceland':'IS',
	'Italy':'IT',
	'Jamaica':'JM',
	'Jordan':'JO',
	'Japan':'JP',
	'Kenya':'KE',
	'Kyrgyzstan':'KG',
	'Cambodia':'KH',
	'Kiribati':'KI',
	'Comoros':'KM',
	'Saint Kitts and Nevis':'KN',
	'Korea, Democratic People\'s Republic of':'KP',
	'Korea, Republic of':'KR',
	'Kuwait':'KW',
	'Cayman Islands':'KY',
	'Kazakhstan':'KZ',
	'Lao People\'s Democratic Republic':'LA',
	'Lebanon':'LB',
	'Saint Lucia':'LC',
	'Liechtenstein':'LI',
	'Sri Lanka':'LK',
	'Liberia':'LR',
	'Lesotho':'LS',
	'Lithuania':'LT',
	'Luxembourg':'LU',
	'Latvia':'LV',
	'Libya':'LY',
	'Morocco':'MA',
	'Monaco':'MC',
	'Moldova, Republic of':'MD',
	'Madagascar':'MG',
	'Marshall Islands':'MH',
	'Macedonia':'MK',
	'Mali':'ML',
	'Myanmar':'MM',
	'Mongolia':'MN',
	'Macau':'MO',
	'Northern Mariana Islands':'MP',
	'Martinique':'MQ',
	'Mauritania':'MR',
	'Montserrat':'MS',
	'Malta':'MT',
	'Mauritius':'MU',
	'Maldives':'MV',
	'Malawi':'MW',
	'Mexico':'MX',
	'Malaysia':'MY',
	'Mozambique':'MZ',
	'Namibia':'NA',
	'New Caledonia':'NC',
	'Niger':'NE',
	'Norfolk Island':'NF',
	'Nigeria':'NG',
	'Nicaragua':'NI',
	'Netherlands':'NL',
	'Norway':'NO',
	'Nepal':'NP',
	'Nauru':'NR',
	'Niue':'NU',
	'New Zealand':'NZ',
	'Oman':'OM',
	'Panama':'PA',
	'Peru':'PE',
	'French Polynesia':'PF',
	'Papua New Guinea':'PG',
	'Philippines':'PH',
	'Pakistan':'PK',
	'Poland':'PL',
	'Saint Pierre and Miquelon':'PM',
	'Pitcairn Islands':'PN',
	'Puerto Rico':'PR',
	'Palestinian Territory':'PS',
	'Portugal':'PT',
	'Palau':'PW',
	'Paraguay':'PY',
	'Qatar':'QA',
	'Reunion':'RE',
	'Romania':'RO',
	'Russian Federation':'RU',
	'Rwanda':'RW',
	'Saudi Arabia':'SA',
	'Solomon Islands':'SB',
	'Seychelles':'SC',
	'Sudan':'SD',
	'Sweden':'SE',
	'Singapore':'SG',
	'Saint Helena':'SH',
	'Slovenia':'SI',
	'Svalbard and Jan Mayen':'SJ',
	'Slovakia':'SK',
	'Sierra Leone':'SL',
	'San Marino':'SM',
	'Senegal':'SN',
	'Somalia':'SO',
	'Suriname':'SR',
	'Sao Tome and Principe':'ST',
	'El Salvador':'SV',
	'Syrian Arab Republic':'SY',
	'Swaziland':'SZ',
	'Turks and Caicos Islands':'TC',
	'Chad':'TD',
	'French Southern Territories':'TF',
	'Togo':'TG',
	'Thailand':'TH',
	'Tajikistan':'TJ',
	'Tokelau':'TK',
	'Turkmenistan':'TM',
	'Tunisia':'TN',
	'Tonga':'TO',
	'Timor-Leste':'TL',
	'Turkey':'TR',
	'Trinidad and Tobago':'TT',
	'Tuvalu':'TV',
	'Taiwan':'TW',
	'Tanzania, United Republic of':'TZ',
	'Ukraine':'UA',
	'Uganda':'UG',
	'United States Minor Outlying Islands':'UM',
	'United States':'US',
	'Uruguay':'UY',
	'Uzbekistan':'UZ',
	'Holy See (Vatican City State)':'VA',
	'Saint Vincent and the Grenadines':'VC',
	'Venezuela':'VE',
	'Virgin Islands, British':'VG',
	'Virgin Islands, U.S.':'VI',
	'Vietnam':'VN',
	'Vanuatu':'VU',
	'Wallis and Futuna':'WF',
	'Samoa':'WS',
	'Yemen':'YE',
	'Mayotte':'YT',
	'Serbia':'RS',
	'South Africa':'ZA',
	'Zambia':'ZM',
	'Montenegro':'ME',
	'Zimbabwe':'ZW',
	'Anonymous Proxy':'A1',
	'Satellite Provider':'A2',
	'Other':'O1',
	'Aland Islands':'AX',
	'Guernsey':'GG',
	'Isle of Man':'IM',
	'Jersey':'JE',
	'Saint Barthelemy':'BL',
	'Saint Martin':'MF',
	'Bonaire, Saint Eustatius and Saba':'BQ'
}
