CREATE TABLE IF NOT EXISTS `reports_profiles` (
		`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
		`name` varchar(256) NOT NULL,
		`description` varchar(512) NOT NULL,
		`fromdate` double NOT NULL,
		`todate` double NOT NULL,
		`app_id` bigint(20) unsigned DEFAULT NULL,
		`user_id` varchar(512) DEFAULT NULL,
		`session_id` varchar(512) DEFAULT NULL,
		`ip` varchar(20) DEFAULT NULL,
		`user_agent_id` varchar(512) DEFAULT NULL,
		`scoreType` varchar(20) NOT NULL,
		`scoreComp` varchar(20) NOT NULL,
		`score` varchar(1024) NOT NULL,
		`startTime` double NOT NULL,
		`endTime` double NOT NULL,
		`Country` varchar(20) DEFAULT NULL,
		`City` varchar(20) DEFAULT NULL,
		`Workflow_name` varchar(20) DEFAULT NULL,
		`Workflow_id` int(11) NOT NULL,
		`page` varchar(100) DEFAULT NULL,
		`page_criterion` varchar(100) DEFAULT NULL,
		PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=127 ;