/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});


Ext.application({

    requires: [
        'MyApp.view.RulesWizard',
        'MyApp.view.changesSaved',
        'MyApp.view.RuleAdded',
        'MyApp.view.DeleteRule',
        'MyApp.view.RequestAttributes',
        'MyApp.view.ProfileSave',
        'MyApp.view.ruleEdited_success',
        'MyApp.view.ruleEdited_failure',
        'MyApp.view.groupEdited_success',
        'MyApp.view.changesSavedError',
        'MyApp.view.i_criterion',
        'MyApp.view.d_suspectsLarge',
        'MyApp.view.appEdit_Error',
        'MyApp.view.w_workflow_record',
        'MyApp.view.d_mapLarge',
        'MyApp.view.add_new_rules_category',
        'MyApp.view.add_new_rules_group',
        'MyApp.view.edit_rules_category',
        'MyApp.view.RequestAttributes_balloon',
        'MyApp.view.a_node_tip',
        'MyApp.view.copy_to_clipboard',
        'MyApp.view.c_training_backup',
        'MyApp.view.rule_type_tooltip',
        'MyApp.view.c_logmode_dialog',
        'MyApp.view.application_wizard',
        'MyApp.view.Dashboard',
        'MyApp.view.Alerts',
        'MyApp.view.Investigate',
        'MyApp.view.Workflow',
        'MyApp.view.Behavior',
        'MyApp.view.Configuration',
        'MyApp.view.main_panel',
        'MyApp.view.About',
        'MyApp.view.ipConfig'
    ],
    stores: [
        'd_rowsNum',
        'd_suspectsStore',
        'd_appsStore',
        'd_refreshStore',
        'alerts',
        'w_extensionsStore',
        'general_flow_group_store',
        'c_exHeadersStore',
        'c_exParamsStore',
        'c_SanitizedStore',
        'c_NetworkIpsStore',
        'c_NetworkUAsStore',
        'c_NetworkExtsStore',
        'a_searchFieldStore',
        'i_filterscoreTypeStore',
        'i_filterComparatorStore',
        'i_profilesStore',
        'i_profiles2Store',
        'i_suspectsStore',
        'b_rgiLiteralFieldStore',
        'b_riFuzzyLengthStore',
        'b_riRuleTypeStore',
        'global_aspect_type_store',
        'b_irScoreType_AStore',
        'b_riTime2_Pat',
        'rw_literal',
        'c_reportTime',
        'i_resultsStore',
        'i_andOrStore',
        'd_trendsScaleStore',
        'rw_geoOutsideChosen',
        'rw_geoInsideChosen',
        'rw_geoOutsideAll',
        'rw_geoInsideAll',
        'b_geoInsideAll',
        'b_geoInsideChosen',
        'b_geoOutsideChosen',
        'b_geoOutsideAll',
        'i_pageStore',
        'c_app_cookieStore',
        'Countries',
        'bot_type_store',
        'b_rulesTreeStore',
        'general_rules_store',
        'alerts_ips',
        'ssl_server_ip_store',
        'c_app_global_pages_store',
        'appAdd_ssl_server_ip_store',
        'app_wizard_cookie_list_store',
        'global_methods_store',
        'c_lb_headers_store',
        'general_appsStore',
        'general_rule_group_categories_store',
        'rw_rule_groups_store',
        'general_rule_groups_store',
        'b_ri_alert_params_store',
        'rw_alert_params_store',
        'RequestAttributes_details',
        'b_ri_group_emails',
        'b_rw_group_emails',
        'c_app_cookie_list_store',
        'app_wizard_global_pages_store',
        'app_wizard_cookieStore',
        'c_ip_whitelist_store',
	'c_ip_ignorelist_store',
        'RequestParameters',
        'RequestScores',
        'a_rulesStore',
        'agents'
    ],
    views: [
        'RulesWizard',
        'changesSaved',
        'RuleAdded',
        'DeleteRule',
        'RequestAttributes',
        'ProfileSave',
        'ruleEdited_success',
        'ruleEdited_failure',
        'groupEdited_success',
        'changesSavedError',
        'i_criterion',
        'd_suspectsLarge',
        'appEdit_Error',
        'w_workflow_record',
        'd_mapLarge',
        'add_new_rules_category',
        'add_new_rules_group',
        'edit_rules_category',
        'RequestAttributes_balloon',
        'a_node_tip',
        'copy_to_clipboard',
        'c_training_backup',
        'rule_type_tooltip',
        'c_logmode_dialog',
        'application_wizard',
        'Dashboard',
        'Alerts',
        'Investigate',
        'Workflow',
        'Behavior',
        'Configuration',
        'main_panel',
        'About',
        'ipConfig'
    ],
    name: 'MyApp',

    launch: function() {
//        Ext.create('MyApp.view.main_panel', {renderTo: Ext.getBody()});
    }

});
