/*
 * File: app/view/groupWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.groupWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.selection.CheckboxModel',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox'
    ],

    height: 528,
    id: 'groupWindow',
    width: 752,
    layout: 'absolute',
    title: 'Group Editor',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save Group',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'group_delete',
                            text: 'Delete Group',
                            listeners: {
                                click: {
                                    fn: me.onGroup_deleteClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'group_activity',
                            text: 'View Activity'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 10,
                    id: 'group_name',
                    width: 240,
                    fieldLabel: 'Name'
                },
                {
                    xtype: 'gridpanel',
                    x: 260,
                    y: 10,
                    height: 180,
                    id: 'group_users',
                    width: 230,
                    title: 'User Selection',
                    store: 'usersStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'login',
                            text: 'User Login',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        checkOnly: true
                    })
                },
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 80,
                    height: 106,
                    id: 'group_description',
                    width: 240,
                    fieldLabel: 'Description',
                    labelAlign: 'top'
                },
                {
                    xtype: 'gridpanel',
                    x: 10,
                    y: 200,
                    height: 260,
                    id: 'group_permissions',
                    width: 480,
                    title: 'Permissions',
                    store: 'permissionsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 70,
                            defaultWidth: 70,
                            dataIndex: 'class',
                            text: 'Scope'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                switch(value) {
                                    case 'get': return 'View'; break;
                                    case 'set': return 'Modify'; break;
                                    case 'add': return 'Create'; break;
                                    case 'del': return 'Delete'; break;
                                }
                            },
                            width: 70,
                            defaultWidth: 70,
                            dataIndex: 'function',
                            text: 'Type'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'description',
                            text: 'Description',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        checkOnly: true
                    })
                },
                {
                    xtype: 'gridpanel',
                    x: 500,
                    y: 10,
                    height: 450,
                    id: 'group_applications',
                    width: 230,
                    title: 'Applications',
                    store: 'applicationsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'domain',
                            text: 'Application',
                            flex: 1
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        checkOnly: true
                    })
                },
                {
                    xtype: 'checkboxfield',
                    x: 10,
                    y: 40,
                    id: 'group_mail_reports',
                    fieldLabel: '',
                    boxLabel: 'Subscribe to reports'
                },
                {
                    xtype: 'checkboxfield',
                    x: 10,
                    y: 60,
                    id: 'group_mail_alerts',
                    fieldLabel: '',
                    boxLabel: 'Subscribe to alerts'
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        telepath.groups.save();
    },

    onGroup_deleteClick: function(button, e, eOpts) {
        telepath.groups.deleteClick();
    }

});