/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Login', {
    extend: 'Ext.window.Window',

    border: 0,
    draggable: false,
    height: 261,
    hidden: false,
    id: 'login',
    margin: '',
    style: 'background-color: white;',
    width: 290,
    constrain: true,
    layout: {
        type: 'absolute'
    },
    bodyStyle: 'background-color: white;',
    closable: false,
    collapseFirst: false,
    title: 'Login',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 110,
                    id: 'login-username',
                    width: 250,
                    fieldLabel: 'Username',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 140,
                    id: 'login-password',
                    width: 250,
                    fieldLabel: 'Password',
                    inputType: 'password',
                    allowBlank: false
                },
                {
                    xtype: 'button',
                    x: 230,
                    y: 200,
                    text: 'Login',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'label',
                    x: 20,
                    y: 200,
                    height: 20,
                    id: 'login-msg',
                    width: 200,
                    text: ''
                },
                {
                    xtype: 'image',
                    x: 10,
                    y: 0,
                    height: 90,
                    width: 260,
                    src: 'images/logo.png'
                },
                {
                    xtype: 'checkboxfield',
                    x: 20,
                    y: 170,
                    id: 'login-remember',
                    fieldLabel: 'Remember Me',
                    labelSeparator: '&nbsp;'
                },
                {
                    xtype: 'container',
                    x: 150,
                    y: 170,
                    height: 20,
                    html: '<a href="#" class="password-reset">Reset Password</a>',
                    width: 120
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        telepath.login.do_login();
    }

});