/*
 * File: app/store/i_suspectsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.i_suspectsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'i_suspectsStore',
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'td0'
                },
                {
                    name: 'td1'
                },
                {
                    name: 'td2'
                },
                {
                    name: 'td3'
                },
                {
                    name: 'td4'
                },
                {
                    name: 'td5'
                },
                {
                    name: 'td6'
                },
                {
                    name: 'td7'
                },
                {
                    name: 'td8'
                },
                {
                    name: 'td9'
                },
                {
                    name: 'td10'
                },
                {
                    name: 'td11'
                },
                {
                    name: 'td12'
                },
                {
                    name: 'td13'
                },
                {
                    name: 'td14'
                },
                {
                    name: 'td15'
                },
                {
                    name: 'td16'
                },
                {
                    name: 'td17'
                },
                {
                    name: 'td18'
                },
                {
                    name: 'td19'
                },
                {
                    name: 'td20'
                },
                {
                    name: 'td21'
                },
                {
                    name: 'td22'
                },
                {
                    name: 'td23'
                },
                {
                    name: 'td24'
                }
            ]
        }, cfg)]);
    }
});