/*
 * File: app/store/RequestParameters.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.RequestParameters', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'RequestParameters',
            proxy: {
                type: 'memory'
            },
            fields: [
                {
                    name: 'type'
                },
                {
                    name: 'id'
                },
                {
                    name: 'td0'
                },
                {
                    name: 'td1'
                },
                {
                    name: 'td2',
                    sortType: 'asInt',
                    type: 'int'
                },
                {
                    name: 'td3'
                },
                {
                    name: 'alias'
                },
                {
                    name: 'noisy'
                },
                {
                    name: 'mask'
                }
            ]
        }, cfg)]);
    }
});