/*
 * File: app/store/rw_geoInsideAll.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.rw_geoInsideAll', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'rw_geoInsideAll',
            proxy: {
                type: 'ajax',
                url: '/js/countries.json',
                reader: {
                    type: 'json',
                    root: 'countries'
                }
            },
            fields: [
                {
                    name: 'Country',
                    sortType: 'asText'
                },
                {
                    name: 'Alias'
                }
            ],
            listeners: {
                load: {
                    fn: me.onJsonstoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreLoad: function(store, records, successful, eOpts) {
        var chosen_store = Ext.getStore('rw_geoInsideChosen');
        chosen_store.each(
            function(record){
                var rec = store.findRecord('Country',record.get('Country'))
                if (rec)
                    store.remove(rec)
            }
        );
    }

});