/*
 * File: app/view/a_node_tip.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.a_node_tip', {
    extend: 'Ext.grid.property.Grid',

    floating: true,
    height: 250,
    id: 'a_node_tip',
    width: 400,
    resizable: true,
    titleCollapse: true,
    enableColumnHide: false,
    hideHeaders: true,
    scroll: 'horizontal',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            source: {
                
            },
            listeners: {
                containermouseout: {
                    fn: me.onA_node_tipContainerMouseOut,
                    scope: me
                },
                render: {
                    fn: me.onA_node_tipRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onA_node_tipContainerMouseOut: function(dataview, e, eOpts) {
        Ext.getCmp('a_node_tip').hide();
    },

    onA_node_tipRender: function(component, eOpts) {
        Ext.getCmp('a_node_tip').getEl().addListener('mouseleave',
        function(){

            component.hide();
        });
    }

});