/*
 * File: app/view/About.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.About', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.Label',
        'Ext.form.field.Display',
        'Ext.Img'
    ],

    height: 242,
    width: 391,
    resizable: false,
    layout: 'absolute',
    title: 'About',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    x: 10,
                    y: 90,
                    height: 110,
                    width: 360,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'label',
                            x: 10,
                            y: 10,
                            cls: 'tp-title',
                            width: 340,
                            text: 'System Revision'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 50,
                            id: 'c_soft_update_date',
                            width: 340,
                            fieldLabel: 'Last updated on',
                            labelSeparator: ' ',
                            labelWidth: 200,
                            value: 'n/a'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 85,
                            hidden: true,
                            id: 'c_soft_atms_revision',
                            width: 340,
                            fieldLabel: 'ATMS revision',
                            labelSeparator: ' ',
                            labelWidth: 200,
                            value: 'n/a'
                        },
                        {
                            xtype: 'displayfield',
                            x: 10,
                            y: 80,
                            id: 'c_soft_engine_revision',
                            width: 340,
                            fieldLabel: 'Engine revision',
                            labelSeparator: ' ',
                            labelWidth: 200,
                            value: 'n/a'
                        }
                    ]
                },
                {
                    xtype: 'image',
                    x: 10,
                    y: 10,
                    height: 70,
                    src: 'images/logo.png'
                }
            ]
        });

        me.callParent(arguments);
    }

});