/*
 * File: app/view/c_logmode_dialog.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.c_logmode_dialog', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Label',
        'Ext.button.Button',
        'Ext.ProgressBar',
        'Ext.container.Container',
        'Ext.form.field.ComboBox'
    ],

    height: 531,
    id: 'c_logmode_dialog',
    width: 560,
    layout: 'absolute',
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    x: 10,
                    y: 370,
                    text: 'Uploading:'
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 420,
                    text: 'Processing:'
                },
                {
                    xtype: 'button',
                    x: 460,
                    y: 470,
                    id: 'c_logmode_cancel',
                    width: 50,
                    text: 'Cancel',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'button',
                    x: 380,
                    y: 470,
                    height: 20,
                    id: 'c_logmode_start',
                    width: 70,
                    text: 'Start',
                    listeners: {
                        click: {
                            fn: me.onButtonClick1,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'progressbar',
                    x: 10,
                    y: 390,
                    id: 'c_logmode_progress_upload',
                    width: 500
                },
                {
                    xtype: 'progressbar',
                    x: 10,
                    y: 440,
                    id: 'c_logmode_progress_engine',
                    width: 500
                },
                {
                    xtype: 'container',
                    x: 10,
                    y: 30,
                    border: '',
                    height: 30,
                    id: 'c_logmode_droparea',
                    width: 300,
                    layout: 'absolute'
                },
                {
                    xtype: 'combobox',
                    x: 10,
                    y: 470,
                    id: 'c_logmode_type',
                    fieldLabel: 'Log Type',
                    value: 'Apache',
                    store: [
                        'IIS',
                        'Apache'
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onC_training_backupShow,
                    scope: me
                },
                destroy: {
                    fn: me.onC_training_backupDestroy,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp('c_logmode_dialog').destroy();
    },

    onButtonClick1: function(button, e, eOpts) {
        logmode_start();
    },

    onC_training_backupShow: function(component, eOpts) {
        Ext.getCmp('main_panel').disable();
    },

    onC_training_backupDestroy: function(component, eOpts) {
        Ext.getCmp('main_panel').enable();
    }

});