/*
 * File: app/view/DateError.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DateError', {
    extend: 'Ext.window.Window',

    draggable: false,
    height: 100,
    id: 'DateError',
    width: 274,
    resizable: false,
    layout: {
        type: 'absolute'
    },
    closable: false,
    title: 'Date Selection Error',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    id: 'date_error',
                    itemId: 'date_error',
                    style: 'font-weight:bold;',
                    width: 240,
                    text: 'Start Date cannot exceed End Date',
                    x: 10,
                    y: 20
                }
            ]
        });

        me.callParent(arguments);
    }

});