/*
 * File: app/view/groupEdited_success.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.groupEdited_success', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.Img',
        'Ext.form.Label'
    ],

    draggable: false,
    height: 137,
    id: 'groupEdited_success',
    width: 351,
    resizable: false,
    layout: 'absolute',
    closable: false,
    title: 'Information',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    x: 40,
                    y: 20,
                    height: 50,
                    width: 50,
                    src: 'Htmls/images/success.gif'
                },
                {
                    xtype: 'label',
                    x: 110,
                    y: 40,
                    style: 'font-weight:bold;',
                    text: 'Rule was saved successfuly'
                }
            ],
            listeners: {
                hide: {
                    fn: me.onGroupEdited_successHide,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onGroupEdited_successHide: function(component, eOpts) {
        //abstractcomponent.destroy();
    }

});