/*
 * File: app/view/rule_type_tooltip.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.rule_type_tooltip', {
    extend: 'Ext.container.Container',

    autoRender: true,
    baseCls: 'x-tip',
    floating: true,
    height: 250,
    html: '<p><br> &#9679; <b>Parameter Rule</b> <br>Rules may be limited to specific applications, specific user names or specific IP addresses. For instance: one may define one rule-set for internal IP addresses, and a different rule-set for external web users.Rules may be limited to specific applications, specific user names or specific IP addresses. For instance: one may define one rule-set for internal IP addresses, and a different rule-set for external web users. 					</p>				    							     					<p> 					<br>&#9679; <b>Behavior Rule</b> <br> Inspect one aspect of the web user\'s behavior such as: landing speed, path, geographic location and so on. This behavior aspect is measured heuristically and compared with known behavior. 					</p> 					<p> 					<br>&#9679;  <b>Pattern Rule</b> <br>Detect repetitive patterns over a predefined period of time. Password brute-force attacks are a good example, for instance: ten different passwords attempted with the same user-name over a period of two minutes. 					</p>',
    id: 'rule_type_tooltip',
    padding: 10,
    width: 670,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});