/*
 * File: app/view/Workflow.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Workflow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.workflow',

    requires: [
        'Ext.form.Label',
        'Ext.Img',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.toolbar.Toolbar'
    ],

    id: 'workflowsPanel',
    itemId: 'workflowsPanel',
    layout: 'fit',
    title: 'Business Actions',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'left',
                    id: 'w_config',
                    minWidth: 300,
                    width: 300,
                    resizable: true,
                    resizeHandles: 'e',
                    layout: 'fit',
                    collapseDirection: 'left',
                    collapsible: true,
                    title: 'Configuration',
                    items: [
                        {
                            xtype: 'container',
                            height: 40,
                            hidden: true,
                            id: 'w_record_sign',
                            style: 'border-color:#FF6A6A;\nborder-style:solid;\nborder-radius:8px;',
                            width: 150,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'label',
                                    x: 40,
                                    y: 10,
                                    height: 20,
                                    style: 'font:\'Tahoma,Arial,Verdana\';\ncolor:#FF6A6A;\nfont-size:15px;',
                                    width: 100,
                                    text: 'RECORDING'
                                },
                                {
                                    xtype: 'image',
                                    x: 5,
                                    y: 5,
                                    height: 30,
                                    width: 30,
                                    src: 'Htmls/images/b_red_larger.gif'
                                }
                            ]
                        },
                        {
                            xtype: 'label',
                            height: 22,
                            hidden: true,
                            style: 'background-color:#EEE;\nfont-weight:bold;',
                            width: 300,
                            text: 'Page Filters'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: 'w_expand_filter',
                            icon: 'Htmls/images/expand_panel.gif',
                            listeners: {
                                click: {
                                    fn: me.w_ext_expand,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'container',
                            border: 0,
                            height: 300,
                            hidden: true,
                            id: 'w_filter_panel',
                            padding: 0,
                            style: 'border-top:0;',
                            width: 300,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'label',
                                    x: 10,
                                    y: 10,
                                    id: 'w_search_label',
                                    style: 'background-color:#EEE;',
                                    width: 280,
                                    text: 'Search Page'
                                },
                                {
                                    xtype: 'textfield',
                                    x: 10,
                                    y: 40,
                                    id: 'w_search_page',
                                    width: 220,
                                    fieldLabel: '',
                                    labelSeparator: ' ',
                                    labelWidth: 50,
                                    allowBlank: false,
                                    emptyText: 'Enter name',
                                    enableKeyEvents: true,
                                    listeners: {
                                        keypress: {
                                            fn: me.onTextfieldKeypress2,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 240,
                                    y: 40,
                                    id: 'w_search',
                                    icon: 'Htmls/images/search.png',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.w_search_click,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 270,
                                    y: 40,
                                    id: 'w_search_cancel',
                                    icon: 'Htmls/images/x.gif',
                                    text: '',
                                    listeners: {
                                        click: {
                                            fn: me.w_search_cancel_click,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'label',
                                    x: 10,
                                    y: 80,
                                    id: 'w_extensions_label',
                                    style: 'background-color:#EEE;',
                                    width: 280,
                                    text: 'Extensions Filter'
                                },
                                {
                                    xtype: 'gridpanel',
                                    x: 10,
                                    y: 120,
                                    height: 140,
                                    id: 'w_extensions',
                                    width: 280,
                                    collapsed: false,
                                    title: '',
                                    forceFit: true,
                                    scroll: 'vertical',
                                    store: 'w_extensionsStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            id: 'w_extensionsCol',
                                            width: 303,
                                            layout: 'anchor',
                                            dataIndex: 'ext',
                                            text: ''
                                        }
                                    ],
                                    selModel: Ext.create('Ext.selection.RowModel', {
                                        mode: 'MULTI'
                                    }),
                                    listeners: {
                                        itemclick: {
                                            fn: me.onW_extensionsItemClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 10,
                                    y: 270,
                                    width: 50,
                                    text: 'Show',
                                    listeners: {
                                        click: {
                                            fn: me.w_show_ext_click,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'panel',
                    id: 'w_diagram',
                    layout: 'absolute',
                    title: 'Diagram',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'w_diagram_toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Reorder Items',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                render: {
                    fn: me.onWorkflowsPanelRender,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    w_ext_expand: function(button, e, eOpts) {
        var panel = Ext.getCmp('w_filter_panel');
        var button_ = Ext.getCmp('w_expand_filter')
        if (panel.hidden){
            Ext.getCmp('w_saved_flows').setPosition(0,500,true)
            panel.show(true)
            button_.setIcon('Htmls/images/collapse_panel.gif')
        }
        else{
            panel.hide(true)
            Ext.getCmp('w_saved_flows').setPosition(0,200,true)
            button_.setIcon('Htmls/images/expand_panel.gif')
        }
    },

    onTextfieldKeypress2: function(textfield, e, eOpts) {
        if (e.keyCode==13)
            search_page()
    },

    w_search_click: function(button, e, eOpts) {
        search_page()
    },

    w_search_cancel_click: function(button, e, eOpts) {
        clear_search()
    },

    onW_extensionsItemClick: function(dataview, record, item, index, e, eOpts) {
        if (record.get('ext')=='Show All'){
            var selectedExts=dataview.getSelectionModel().getSelection();
            Ext.getCmp('w_extensions').getView().select(0);
        }
        else{
            Ext.getCmp('w_extensions').getView().deselect(0);
            var selectedExts=dataview.getSelectionModel().getSelection();
        }
    },

    w_show_ext_click: function(button, e, eOpts) {
        update_graph_by_extensions()
    },

    onButtonClick: function(button, e, eOpts) {
        telepath.workflow.diagram.reorder();
    },

    onWorkflowsPanelRender: function(component, eOpts) {
        new Ext.LoadMask(component,{ msg:"Loading Workflow...",id:"workflow_mask"});

    }

});